AWSTemplateFormatVersion: "2010-09-09"

Description: CodePipeline to execute CloudFormation CICD.

Parameters:
  CodeCommitArn:
    Type: String

  CfnConfigFilePath:
    Type: String

  # NOTE: Pass your buildspec.yml like
  # rain deploy cfn-execution-pipeline.yaml \
  #             -c config/local.yaml \
  #             --params BuildSpecCi=$(cat buildspec/buildspec-ci.yml)
  BuildSpecCi:
    Type: String

  BuildSpecCreateChangeSet:
    Type: String

  BuildSpecDeploy:
    Type: String

Resources:

  # -----------------------------------------------------------------
  # CodePipeline
  # -----------------------------------------------------------------

  ### IAM Role - CodePipeline service role
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-pipeline-codepipeline-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: IAM Role for CodePipeline service role.

  CodePipelineServiceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cfn-pipeline-codepipeline-service-role-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Action: sts:AssumeRole
            Resource: '*' # TODO: replace to arn of action roles
      Roles:
        - !Ref CodePipelineServiceRole

  ### IAM Role - CodePipeline action role: Source
  CodePipelineActionSourceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-pipeline-codepipeline-action-source-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt CodePipelineServiceRole.Arn
            Action:
              - sts:AssumeRole
      Description: IAM Role for CodePipeline action role - source.

  CodePipelineActionSourceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cfn-pipeline-codepipeline-action-source-role-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCodeCommitAccess
            Effect: Allow
            Action:
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:GetUploadArchiveStatus
              - codecommit:UploadArchive
              - codecommit:CancelUploadArchive
            Resource:
              - !Ref CodeCommitArn
      Roles:
        - !Ref CodePipelineActionSourceRole

  # -----------------------------------------------------------------
  # Artifact store
  # -----------------------------------------------------------------

  ### S3
  ArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cfn-execution-pipeline-artifact-store-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref ArtifactStoreKey
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ### KMS
  ArtifactStoreKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/cfn-pipeline-artifact-store-key
      TargetKeyId: !Ref ArtifactStoreKey

  ArtifactStoreKey:
    Type: AWS::KMS::Key
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - I3042
    Properties:
      Description: For cfn pipeline artifact store
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCodeCommitAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: '*'
            Resource: '*'

  # -----------------------------------------------------------------
  # CodeBuild - CI action
  # -----------------------------------------------------------------

  ### CodeBuild for CI action
  CodeBuildActionCI:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: cfn-pipeline-ci-action
      Description: For cfn pipeline CI action.
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: CFN_CONFIG_FILE_PATH
            Value: !Ref CfnConfigFilePath
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
      ServiceRole: !Ref CodeBuildActionCIRole
      Source:
        BuildSpec: !Ref BuildSpecCi
        Type: CODEPIPELINE

  ### IAM Role for CI action
  CodeBuildActionCIRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-pipeline-codebuild-action-ci-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: IAM Role for CodePipeline action role - CI.

  CodeBuildActionCIRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cfn-pipeline-codebuild-action-ci-role-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudWatchAccess
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - '*'
          - Sid: AllowArtifactStoreAccess
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub
              - ${S3Arn}/*
              - S3Arn: !GetAtt ArtifactStore.Arn
          - Sid: AllowKMSAccess
            Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:ReEncrypt*
              - kms:GenerateDatakey*
            Resource: !GetAtt ArtifactStoreKey.Arn
      Roles:
        - !Ref CodeBuildActionCIRole

  # -----------------------------------------------------------------
  # CodeBuild - CreateChangeSet action
  # -----------------------------------------------------------------

  ### CodeBuild for CreateChangeSet action
  CodeBuildActionCreateChangeSet:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: cfn-pipeline-create-change-set-action
      Description: For cfn pipeline CreateChangeSet action.
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: CFN_CONFIG_FILE_PATH
            Value: !Ref CfnConfigFilePath
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
      ServiceRole: !Ref CodeBuildActionCreateChangeSetRole
      Source:
        BuildSpec: !Ref BuildSpecCreateChangeSet
        Type: CODEPIPELINE

  ### IAM Role for CreateChangeSet action
  CodeBuildActionCreateChangeSetRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-pipeline-codebuild-action-create-change-set-role
      Description: IAM Role for CodePipeline action role - CreateChangeSet.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole

  CodeBuildActionCreateChangeSetRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cfn-pipeline-codebuild-action-create-change-set-role-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudWatchAccess
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - '*'
          - Sid: AllowArtifactStoreAccess
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub
              - ${S3Arn}/*
              - S3Arn: !GetAtt ArtifactStore.Arn
          - Sid: AllowKMSAccess
            Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:ReEncrypt*
              - kms:GenerateDatakey*
            Resource: !GetAtt ArtifactStoreKey.Arn
          - Sid: AllowCloudFormationAccess
            Effect: Allow
            Action:
              - cloudformation:ListStacks
              - cloudformation:DescribeStacks
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeChangeSet
            Resource:
              - '*'
      Roles:
        - !Ref CodeBuildActionCreateChangeSetRole

  # -----------------------------------------------------------------
  # CodeBuild - Deploy action
  # -----------------------------------------------------------------

  ### CodeBuild for Deploy action
  CodeBuildActionDeploy:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: cfn-pipeline-deploy-action
      Description: For cfn pipeline Deploy action.
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: CFN_CONFIG_FILE_PATH
            Value: !Ref CfnConfigFilePath
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
      ServiceRole: !Ref CodeBuildActionDeployRole
      Source:
        BuildSpec: !Ref BuildSpecDeploy
        Type: CODEPIPELINE

  ### IAM Role for Deploy action
  CodeBuildActionDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-pipeline-codebuild-action-deploy-role
      Description: IAM Role for CodePipeline action role - Deploy.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
