AWSTemplateFormatVersion: "2010-09-09"

Description: CodePipeline to execute CloudFormation CICD.

Parameters:
  CodeCommitArn:
    Type: String

Resources:

  # -----------------------------------------------------------------
  # CodePipeline
  # -----------------------------------------------------------------

  ### IAM Role - CodePipeline service role
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-pipeline-codepipeline-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: IAM Role for CodePipeline service role.

  CodePipelineServiceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cfn-pipeline-codepipeline-service-role-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Action: sts:AssumeRole
            Resource: '*' # TODO: replace to arn of action roles
      Roles:
        - !Ref CodePipelineServiceRole

  ### IAM Role - CodePipeline action role: Source
  CodePipelineActionSourceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cfn-pipeline-codepipeline-action-source-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt CodePipelineServiceRole.Arn
            Action:
              - sts:AssumeRole
      Description: IAM Role for CodePipeline action role - source.

  CodePipelineActionSourceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cfn-pipeline-codepipeline-action-source-role-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCodeCommitAccess
            Effect: Allow
            Action:
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:GetUploadArchiveStatus
              - codecommit:UploadArchive
              - codecommit:CancelUploadArchive
            Resource:
              - !Ref CodeCommitArn
      Roles:
        - !Ref CodePipelineActionSourceRole

  # -----------------------------------------------------------------
  # Artifact store
  # -----------------------------------------------------------------

  ### S3
  CodePipelineArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cfn-execution-pipeline-artifact-store-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref ArtifactStoreKey
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ### KMS
  ArtifactStoreKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/cfn-pipeline-artifact-store-key
      TargetKeyId: !Ref ArtifactStoreKey

  ArtifactStoreKey:
    Type: AWS::KMS::Key
    Properties:
      Description: For cfn pipeline artifact store
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCodeCommitAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: '*'
            Resource: '*'
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - I3042