deploy-with-local:
	rain deploy cfn-execution-pipeline-native-cfn-action-pattern.yaml \
		-c config/local.json \
		-y

deploy-with-dev:
	rain deploy cfn-execution-pipeline-native-cfn-action-pattern.yaml \
		-c config/dev.json \
		-y
